In [6]:
from bs4 import BeautifulSoup
import requests
for i in range(1,3):
    url = BeautifulSoup(f'http://www.nepalstock.com/main/floorsheet/index/{i}/','html.parser')

    response = requests.get(url) # requesting for the website
    data = response.text          # converting into string formate
    soup = BeautifulSoup(data,'lxml') # changing into lxml 


    tags = soup.table
    tag = tags.find_all('tr', align = False)

    list1 = []
    for i in range(len(tag)):
        x = tag[i].get_text()
        list1.append(x)

    list2 = []
    for i in range(len(list1)):
        x = list1[i].split("\n")
        list2.append(x[1:-1])
  #list2
    list2 =  list2[0:-3]

    import csv
    xlen = len(list2)
    with open("StockPrice1.csv","a") as csvFile:
    for i in range(xlen):
        writer = csv.writer(csvFile)
        writer.writerow(list2[i])

/usr/local/lib/python3.6/dist-packages/bs4/__init__.py:336: UserWarning: "http://www.nepalstock.com/main/floorsheet/index/1/" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
/usr/local/lib/python3.6/dist-packages/bs4/__init__.py:336: UserWarning: "http://www.nepalstock.com/main/floorsheet/index/2/" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

In [9]:
import plotly.express as px
import pandas as pd

df = pd.read_csv("StockPrice1.csv")

# df = px.data.gapminder().query("year == 2007").query("continent == 'Europe'")
# df.loc[df['pop'] < 2.e6, 'country'] = 'Other countries' # Represent only large countries
# fig = px.pie(df, values='pop', names='country', title='Population of European continent')
# fig.show()

    S.N.       Contract No  Stock Symbol  ...  Quantity  Rate     Amount
0      1  2020020601012901           EIC  ...        10   449    4490.00
1      2  2020020601012902          CCBL  ...       879   188  165252.00
2      3  2020020601012903         SLICL  ...       300   463  138900.00
3      4  2020020601012904           NBB  ...       500   208  104000.00
4      5  2020020601012905          RMDC  ...        50   670   33500.00
5      6  2020020601012906          PPCL  ...        30   126    3780.00
6      7  2020020601012907          ADBL  ...        10   386    3860.00
7      8  2020020601012908           NIL  ...        40   556   22240.00
8      9  2020020601012909          PLIC  ...        40   574   22960.00
9     10  2020020601012910           HDL  ...        10  1220   12200.00
10    11  2020020601012911          PLIC  ...       100   574   57400.00
11    12  2020020601012912           MBL  ...       300   234   70200.00
12    13  2020020601012913           MBL  ...       100   234   23400.00
13    14  2020020601012914           MBL  ...       500   234  117000.00
14    15  2020020601012915           MBL  ...       500   234  117000.00
15    16  2020020601012916           MBL  ...       500   234  117000.00
16    17  2020020601012917           MBL  ...       100   234   23400.00
17    18  2020020601012918           NEF  ...      1127  8.16    9196.32
18    19  2020020601012919          PRVU  ...       196   245   48020.00
19    20  2020020601012920          PRVU  ...      1000   245  245000.00
20  S.N.       Contract No  Stock Symbol  ...  Quantity  Rate     Amount
21    21  2020020601012921          PRVU  ...       557   245  136465.00
22    22  2020020601012922          NICA  ...       453   481  217893.00
23    23  2020020601012923          BOKL  ...       180   235   42300.00
24    24  2020020601012924         NADEP  ...        10   701    7010.00
25    25  2020020601012925          NICL  ...       953   439  418367.00
26    26  2020020601012926          NICL  ...       100   438   43800.00
27    27  2020020601012927          NICL  ...       200   438   87600.00
28    28  2020020601012928          NICL  ...       147   438   64386.00
29    29  2020020601012929          NCCB  ...        10   196    1960.00
30    30  2020020601012930           CBL  ...       200   153   30600.00
31    31  2020020601012931          RMDC  ...        10   670    6700.00
32    32  2020020601012932         SLICL  ...        50   463   23150.00
33    33  2020020601012933          LGIL  ...       122   492   60024.00
34    34  2020020601012934          LGIL  ...        78   491   38298.00
35    35  2020020601012935          LGIL  ...       400   491  196400.00
36    36  2020020601012936         GLICL  ...        20   769   15380.00
37    37  2020020601012937          SICL  ...       100  1145  114500.00
38    38  2020020601012938         SWBBL  ...        20  1130   22600.00
39    39  2020020601012939           SMB  ...        10  1086   10860.00
40    40  2020020601012940          PRIN  ...       100   441   44100.00

[41 rows x 8 columns]